# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald
  font: serif
i_am_a_sponsor: true

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Dr. July Pilowsky'
    description: 'Academic website of July Pilowsky.'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    show_search: true
    fixed_to_top: true
    show_theme_chooser: true
    show_logo: true
    highlight_active_link: true

# Site footer
footer:
  copyright:
    notice: '© {year} Dr. July Pilowsky. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: '2 Jan, 2006'
  time_format: '3:04 PM'

# Site features
features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/japilo/personal-website'
    content_dir: content
    branch: master